# Mongo-Sync Configurations

local:
  db: 'strapi-mongod-farmaplus'
  host:
    port: 27017
  access:
    username: 'admin'
    password: '290603gading'

remote:
  db: 'strapi-mongod-farmaplus'
  host:
    url: '192.168.10.78'
    port: 27017
  access:
    username: 'admin'
    password: '290603gading'

tunnel:
  on: false
  access:
    username: 'remote_ssh_user'
    port: 22

# For now :local just
# assumes DB is at localhost:port

# All of the parameters above are required,
# without them, the script will fail
